### ISSUE TITLE
APN detection

### ISSUE THREAD

**Issue by PavelRykov** [pbakondy/cordova-plugin-sim#28]
Good morning, @pbakondy !

As i know the "cordova-plugin-sim" can detect MCC, MNC and many other things. But i cant see how to get my APN settings. Is it possible to implement a solution to obtain APN settings (name, login and password)?

Thank you in advance.

**Comment by pbakondy** [comment]
Sorry, it is not possible.

## Android

APN settings is not accessible for 3rd party applications since API 14

- https://stackoverflow.com/questions/8714964/ice-cream-sandwich-and-write-apn-settings
- https://stackoverflow.com/a/3477237

## iOS

"Third-party apps don't get that level of control over the hardware"

- http://stackoverflow.com/questions/2665356/how-to-change-iphone-apn-access-point-name-programmatically
- https://ceraos-dharaharsh.blogspot.hu/2013/09/how-to-set-up-cellular-apn.html

## Win

"Apps cannot touch APN. That is the realm of the user, OEM and mobile operators."

- https://social.msdn.microsoft.com/Forums/windowsapps/en-US/e1c20ecb-e53a-4724-80b2-c768a4dcadca/accessing-apn-access-point-name-settings-in-windows-phone-8?forum=wpdevelop

**Comment by PavelRykov** [comment]
@pbakondy yes, but what about reading of apn settings? it is prohibited too?
